### ISSUE TITLE
Validate "traefik" as the application proxy to take care of routing

### ISSUE THREAD

**Issue by notABluesSinger** [soundengineering/infrastructure#4]
Resources:
- https://traefik.io/traefik/
- https://www.heyvaldemar.com/install-portainer-using-docker-compose/
- https://github.com/heyValdemar/portainer-traefik-letsencrypt-docker-compose

**Comment by notABluesSinger** [comment]
Resources:
- https://traefik.io/traefik/
- https://www.heyvaldemar.com/install-portainer-using-docker-compose/

**Comment by notABluesSinger** [comment]
Having now played around with real life urls, this looks like a great solution.
It takes care of
- let's encrypt ssl certs
- sub domain routing for exposed services
- metrics (need to validate which ones)

It will be easy to create new services with only a single change to the main docker compose file and no need to create new infrastructure

**Comment by notABluesSinger** [comment]
Only blocker is that a wildcard dns is required and dream host do not support this - investigating alternate solutions (other domain name or other provider)

**Comment by bennybtl** [comment]
This solution looks pretty sweet and we avoid dealing with ALB or nginx conf.

**Comment by notABluesSinger** [comment]
the main docker compose on the host instance is located in `/srv/containers/traefikPortainer/`
